export type DesignColorToken =
  | 'primary_100'
  | 'primary_90'
  | 'primary_80'
  | 'primary_70'
  | 'primary_60'
  | 'primary_50'
  | 'dark_blue_100'
  | 'dark_blue_90'
  | 'dark_blue_80'
  | 'dark_blue_70'
  | 'dark_blue_60'
  | 'orange_100'
  | 'orange_90'
  | 'orange_80'
  | 'orange_70'
  | 'orange_60'
  | 'orange_50'
  | 'black_100'
  | 'black_80'
  | 'black_60'
  | 'black_40'
  | 'black_20'
  | 'black_10'
  | 'white_100'
  | 'white_95'
  | 'white_90'
  | 'white_98'

export type TypographyToken =
  | 'display'
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'body1'
  | 'body2'
  | 'body3'
  | 'body4'
  | 'caption_10'
  | 'caption_9'

export type ButtonVariant = 'primary' | 'secondary' | 'tertiary' | 'ghost' | 'danger'
export type ButtonSize = 'lg' | 'sm'
export type TabState = 'enable' | 'disable'

